version: '3.4'

services:
  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"

  servico01:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"

  servico02:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"